name: Despliegue de Frontend a Firebase

on:
  push:
    branches:
      - development

jobs:
  # ------------------------------
  # TRABAJO DE PRUEBAS (CI)
  # ------------------------------
  test:
    name: 1. Pruebas Unitarias (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Sacar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Correr pruebas (headless)
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  # ------------------------------
  # TRABAJO DE DESPLIEGUE (CD)
  # ------------------------------
  deploy:
    name: 2. Desplegar en Firebase (CD)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Sacar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir la App (Build)
        run: npm run build -- --configuration production

      - name: Desplegar en Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # El secreto que ya creaste (FIREBASE_TOKEN)
          repoToken: ${{ secrets.GITHUB_TOKEN }} 
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          channelId: live
          # El ID de tu proyecto de Firebase
          projectId: plat-epa